### PR TITLE
Fix Windows build

### LINKED ISSUE #122: Compiling on MacOS: Undefined symbols for architecture arm64:  "dummy_register()"
I might be doing something wrong but when following the instructions in the README I encountered the following on MacOS:

```
❯ cmake --build build --config Release                                                                             (base) 
[ 13%] Built target ggml-base
[ 20%] Built target ggml-metal
[ 31%] Built target ggml-cpu
[ 34%] Built target ggml-blas
[ 39%] Built target ggml
[ 74%] Built target tts
[ 75%] Linking CXX executable ../../bin/tts-cli
ld: warning: ignoring duplicate libraries: '../../ggml/src/libggml.a'
Undefined symbols for architecture arm64:
  "dummy_register()", referenced from:
      __GLOBAL__sub_I_loaders.cpp in libtts.a[10](loaders.cpp.o)
ld: symbol(s) not found for architecture arm64
c++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/tts-cli] Error 1
make[1]: *** [examples/cli/CMakeFiles/tts-cli.dir/all] Error 2
make: *** [all] Error 2
```

In order to get around this I changed `src/models/CMakeLists.txt` from:

```
target_sources(tts PRIVATE
        loaders.cpp
        loaders.h
)

add_subdirectory(dia)
if (LINUX)
    add_subdirectory(dummy)
endif ()
add_subdirectory(kokoro)
add_subdirectory(orpheus)
add_subdirectory(parler)
```

to:

```
target_sources(tts PRIVATE
        loaders.cpp
        loaders.h
)

add_subdirectory(dia)
add_subdirectory(dummy)
add_subdirectory(kokoro)
add_subdirectory(orpheus)
add_subdirectory(parler)
```

After that everything compiles and works. I'm wondering why this was limited only to Linux but my guess is that it has to do with espeak (which I am not using). Happy to submit a PR if this solution is okay.

### PR DESCRIPTION
**Pull request by mrexodia**
- Automatically fetch SDL2 if it cannot be found
- Use `std::numbers::pi` instead of non-standard `M_PI` to fix `dummy` build
- Use `path.string()` where needed to fix compilation

### CODE REVIEW

File: src/models/dummy/model.cpp [hunk 1]
```diff
@@ -1,6 +1,6 @@
 #include "model.h"
 
-#include <cmath>
+#include <numbers>
```
Comment (danielzgtg) [inline src/models/dummy/model.cpp:4]: Thank you for this solution.

While we're at it, could you do the same thing to `src/models/kokoro/model.cpp` and `src/util.cpp` please? Then try removing `#define _USE_MATH_DEFINES` from `src/util.h`

File: examples/cli/CMakeLists.txt [hunk 2]
```diff
@@ -10,10 +10,19 @@ add_executable(${TARGET}
     vad.h
 )
 
-find_package(SDL2)
-if (SDL2_FOUND)
-    target_link_libraries(${TARGET} PRIVATE SDL2::SDL2)
-    set_source_files_properties(playback.cpp PROPERTIES COMPILE_FLAGS -DSDL2_INSTALL=1)
+find_package(SDL2 QUIET)
```
Comment (danielzgtg) [inline examples/cli/CMakeLists.txt]: Some users want this to remain an optional dependency that isn't linked into the final build. See whisper.cpp's `option(WHISPER_SDL2 "whisper: support for libSDL2" OFF)`, and please adapt that to this file

**Review by danielzgtg — CHANGES_REQUESTED** [review]
I reproduced the `.string()` problem, thank you for fixing our oversight of tts-server!

I made two minor suggestions for improvement.

**Comment by danielzgtg** [comment]
@mmwillet Pinging as this will use your CI minutes.

I plan to merge after 24 hours, despite the Windows runner being projected to more than triple the minutes used, because we weren't using many CI minutes to begin with.

File: examples/cli/CMakeLists.txt (hunk 2 above)
Comment (mrexodia) [reply examples/cli/CMakeLists.txt]: I added `TTS_CLI_SDL` that you can turn off for this use case

File: src/models/dummy/model.cpp (hunk 1 above)
Comment (mrexodia) [reply src/models/dummy/model.cpp:4]: Done!

File: src/models/dummy/model.cpp [hunk 3]
```diff
@@ -9,10 +9,10 @@ void dummy_runner::generate(const char * sentence, tts_response & output, const
     const size_t N{ strlen(sentence) };
     outputs = make_unique_for_overwrite<float[]>(output.n_outputs = N * SAMPLING_RATE);
     for (size_t i{}; i < N; ++i) {
-        const float wavelength{static_cast<float>(SAMPLING_RATE / M_PI / 2) / (200 + sentence[i]) };
+        const float wavelength{static_cast<float>(SAMPLING_RATE / std::numbers::pi / 2) / (200 + sentence[i]) };
         float *     buf = &outputs[i * SAMPLING_RATE];
         for (size_t j{}; j < SAMPLING_RATE; ++j) {
-            buf[j] = sin(j * static_cast<float>(M_PI / SAMPLING_RATE)) * sin(j / wavelength);
+            buf[j] = sin(j * static_cast<float>(std::numbers::pi / SAMPLING_RATE)) * sin(j / wavelength);
```
Comment (danielzgtg) [inline src/models/dummy/model.cpp:16]:
```
====================[ Build | tts-cli | Release ]===============================
/usr/bin/cmake --build /home/home/CLionProjects/TTS-cpp/TTS.cpp/cmake-build-release --target tts-cli -j 22
[1/9] Building CXX object src/CMakeFiles/tts.dir/models/dummy/model.cpp.o
FAILED: src/CMakeFiles/tts.dir/models/dummy/model.cpp.o 
ccache /usr/bin/c++ -DGGML_USE_CPU -I/home/home/CLionProjects/TTS-cpp/TTS.cpp/src/. -I/home/home/CLionProjects/TTS-cpp/TTS.cpp/src/../include -I/home/home/CLionProjects/TTS-cpp/TTS.cpp/src/../ggml/src -I/home/home/CLionProjects/TTS-cpp/TTS.cpp/ggml/src/../include -I/home/home/CLionProjects/TTS-cpp/TTS.cpp/ggml-patches -O3 -DNDEBUG -std=c++20 -fdiagnostics-color=always -MD -MT src/CMakeFiles/tts.dir/models/dummy/model.cpp.o -MF src/CMakeFiles/tts.dir/models/dummy/model.cpp.o.d -o src/CMakeFiles/tts.dir/models/dummy/model.cpp.o -c /home/home/CLionProjects/TTS-cpp/TTS.cpp/src/models/dummy/model.cpp
/home/home/CLionProjects/TTS-cpp/TTS.cpp/src/models/dummy/model.cpp: In member function ‘virtual void dummy_runner::generate(const char*, tts_response&, const generation_configuration&)’:
/home/home/CLionProjects/TTS-cpp/TTS.cpp/src/models/dummy/model.cpp:15:22: error: ‘sin’ was not declared in this scope
   15 |             buf[j] = sin(j * static_cast<float>(std::numbers::pi / SAMPLING_RATE)) * sin(j / wavelength);
      |                      ^~~
[5/9] Linking CXX static library ggml/src/libggml-base.a
ninja: build stopped: subcommand failed.
```

**Review by danielzgtg — CHANGES_REQUESTED** [review]

File: src/models/dummy/model.cpp (hunk 3 above)
Comment (mrexodia) [reply src/models/dummy/model.cpp:16]: Yeah makes sense, `sin` is not present in `<cmath>`, I changed it to `math.h` so you can try if that works!

**Comment by ecyht2** [comment]
I do have Windows VMs, I might be able to test it out. @mrexodia, are you using msvc or mingw?

Edit: Whoops probably should read the code first.

File: .github/workflows/build.yml [hunk 4]
```diff
@@ -58,3 +58,16 @@ jobs:
...
+    runs-on: windows-latest
+    steps:
+    - uses: actions/checkout@v5
+      with:
+        submodules: recursive
+    - name: Enable Developer Command Prompt
+      uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
+    - name: build
+      run: |
+        cmake -B build -G Ninja -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl -DCMAKE_BUILD_TYPE=Debug
```
Comment (ecyht2) [inline .github/workflows/build.yml]: Can you change it to not be compile the Debug build?

File: .github/workflows/build.yml [hunk 5]
```diff
@@ -58,3 +58,16 @@ jobs:
...
         path: ${{ steps.strings.outputs.build-output-dir }}
+
+  build-windows:
+    runs-on: windows-latest
+    steps:
+    - uses: actions/checkout@v5
+      with:
+        submodules: recursive
+    - name: Enable Developer Command Prompt
+      uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
```
Comment (ecyht2) [inline .github/workflows/build.yml:69]: I am not sure how does mingw (gcc) compare to MSVC? Is it commonly used, if so can you add the workflow for that as well?

**Comment by mrexodia** [comment]
I am using MSVC. If you want to test you can use a zig toolchain: https://github.com/mrexodia/zig-cross

File: .github/workflows/build.yml (hunk 5 above)
Comment (mrexodia) [reply .github/workflows/build.yml:69]: I do not think mingw is useful or representative for a Windows environment, it seems entirely pointless to add it to me.

File: .github/workflows/build.yml (hunk 4 above)
Comment (mrexodia) [reply .github/workflows/build.yml]: I just did what the Linux build did above, should I also change that to build in Debug mode?

File: .github/workflows/build.yml (hunk 5 above)
Comment (ecyht2) [reply .github/workflows/build.yml:69]: Alright then leave it as is.

File: .github/workflows/build.yml (hunk 4 above)
Comment (ecyht2) [reply .github/workflows/build.yml]: Yup, please do. I am not sure why I put it in Debug mode in the first place.

**Review by ecyht2 — COMMENTED** [review]
Can you also update the README.md to show that we have Windows support?

File: .github/workflows/build.yml (hunk 4 above)
Comment (mrexodia) [reply .github/workflows/build.yml]: Sorry I misread your comment. I used `Debug` mode because it is faster to compile than release mode and I saw you were worried about CI minutes. Will change it to Release.

**Comment by mrexodia** [comment]
> Can you also update the README.md to show that we have Windows support?

I do not know what to change in the feature matrix because I did not test everything. I think this should be done by one of the maintainers and not a random contributing some minor compilation fixes 😅

**Comment by mrexodia** [comment]
I also fixed the Linux build, tested locally with Ubuntu 24.04 LTS

File: .github/workflows/build.yml [hunk 6]
```diff
@@ -58,3 +58,16 @@ jobs:
...
+    - name: build
+      run: |
+        cmake -B build -G Ninja -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl -DCMAKE_BUILD_TYPE=Release
+        cmake --build build
```
Comment (ecyht2) [inline .github/workflows/build.yml:73]:
```suggestion
        cmake --build build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}-msvc-build
        path: build/
```

Comment (ecyht2) [reply .github/workflows/build.yml:73]: I noticed that the build is not producing any artifacts.

Comment (mrexodia) [reply .github/workflows/build.yml:73]: I didn't really see a reason to. It is a C++ library and you would only be able to consume it from the same major Visual Studio version that produced it. Plus the proposed changes don't install the library, so you are just packaging a bunch of obj files that nobody is going to use?

The goal of the PR was to get it to build on Windows, I think project-organizational issues should be addressed later.

Comment (ecyht2) [reply .github/workflows/build.yml:73]: The build process also produces executable files from the examples like the `tts-cli` and `tts-server`. I want to try out their functionalities. Furthermore, the pipeline can also be used to publish pre-built binaries (libraries included) so that users can use the libraries without building it themselves.

Edit: Syntax

Comment (mrexodia) [reply .github/workflows/build.yml:73]: Yes it can be used, but that is not what the `build` folder contains. You have the `cmake --install` feature for this, which creates an install prefix that contains just those artifacts and not a bunch of irrelevant data.
